[tool.ruff]

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 120
output-format = "full"
target-version = "py312"

[tool.ruff.lint]
select = [
    "E", "F", "W", "I", "N", "UP", "YTT", "ANN", "ASYNC", "S", "BLE", "FBT", "B", "A", "COM", "C4", "DTZ",
    "T10", "DJ", "EM", "EXE", "FA", "ISC", "ICN", "LOG", "G", "INP", "PIE", "T20", "PYI", "Q", "RSE", "RET", "SLF",
    "SLOT", "SIM", "TCH", "INT", "ARG", "PTH", "TD", "ERA", "PD", "PGH", "PL", "TRY", "FLY", "NPY", "AIR", "PERF",
    "RUF", "TID", "D", "C90"
]
ignore = [
    "COM812",  # Checks for the absence of trailing commas.
    "D100",  # Checks for undocumented public module definitions.
    "D101",  # Checks for undocumented public class definitions.
    "D102",  # Checks for undocumented public method definitions.
    "D103",  # Checks for undocumented public function definitions.
    "D104",  # Checks for undocumented public package definitions.
    "D105",  # Checks for undocumented magic method definitions.
    "D107",  # Checks for public __init__ method definitions that are missing docstrings.
    "D200",  # Checks for single-line docstrings that are broken across multiple lines.
    "D203",  # Checks for docstrings on class definitions that are not preceded by a blank line.
    "D205",  # Checks for docstring summary lines that are not separated from the docstring description by one blank line.
    "D212",  # Checks for docstring summary lines that are not positioned on the first physical line of the docstring.
    "D401",  # Checks for docstring first lines that are not in an imperative mood.
    "D404",  # Checks for docstrings that start with "This".
    "TD002",  # Checks that a TODO comment includes an author.
    "TD003",  # Checks that a TODO comment is associated with a link to a relevant issue or ticket.
    "TID252",  # Checks for relative imports.
]

[tool.ruff.lint.flake8-annotations]
mypy-init-return = true

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.format]
quote-style = "single"
